### ISSUE TITLE
Receiving Indicate Messages From Remote Module

### ISSUE THREAD

**Issue by YueBit** [ahouben/BleDriver.NET#10]
Hi ahouben,

Thanks for your codes and it does help.

With this driver, now I can send the command from BLED112 dongle to the remote and receive the response from the remote.

But I didn't find how to receive messages (e.g. Indicate messages) from the remote. Could you please tell me how to use the driver to receive the messages from the remote?

Thanks in advance for your answer.

Best regards,
Yue

**Comment by ahouben** [comment]
Hi @NBCY, you closed the issue. Does that mean you found an answer in the meantime ?
