### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by LuisCRSousa** [ahouben/BleDriver.NET#3]
System.ArgumentException: The offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

BgApi.cs:line 251
BgApi.cs:line 308

This happens when I have more than 30-40 beacons.

**Comment by pigrew** [comment]
Patch attached.
[rx_buff_overflow_fix.txt](https://github.com/ahouben/BleDriver.NET/files/321948/rx_buff_overflow_fix.txt)
