### ISSUE TITLE
Windows SerialPort bug due to closing and opening the SerialPort quickly

### ISSUE THREAD

**Issue by pigrew** [ahouben/BleDriver.NET#7]
The Open() function quickly closes the serial port, and then reopens it. On Windows, this can cause exceptions to be thrown. See [this StackOverflow post](http://stackoverflow.com/questions/6434297/why-thread-sleep-before-serialport-open-and-close).

To correct this, don't close and reopen the serial port.

**Comment by ahouben** [comment]
Hi @pigrew, sorry for the delay (5 years OMG)! It seems the fix from @chrisgl addresses your issue by providing an additional `resetUsbDevice` parameter. Will close this issue for now unless you object.

**Comment by pigrew** [comment]
@ahouben , thanks for getting back to this... It looks like it fixes the issue (but I'm not in a position to test it). No objections from me.
