### ISSUE TITLE
Connect Bluetooth Device to BLE dongle

### ISSUE THREAD

**Issue by aadewojo** [ahouben/BleDriver.NET#8]
Hi there,
I have recently used your driver. However I am not sure how to establish connection between the BLE dongle and the bluetooth device.

Can you advice me on this.

Thanks.

**Comment by ahouben** [comment]
Sorry for the late reply!

Yes, I should probably add some example code. I'm just not working on this project at the moment.

**Comment by ahouben** [comment]
Hi @aadewojo,

you've probably moved on, but there's now an example on how to establish a connection to a BLE device from the dongle at https://github.com/ahouben/BleDriver.NET/blob/191cf9507d8c9440eaa3537c0d8ed21e4d712f1a/tests/CommandTests.cs#L104.
