### ISSUE TITLE
Concurrent connections to peripherals

### ISSUE THREAD

**Issue by jainchethan87** [ahouben/BleDriver.NET#9]
Does the source code support concurrent connections? One bluegiga dongle (central) connected to more than one peripheral at the same time? 

If no, any idea what is the effort required to do the same?

Thanks in advance

**Comment by ahouben** [comment]
Yes, it supports concurrent connections, see https://github.com/ahouben/BleDriver.NET/blob/7f9154a69bd923695e55ed9a973653cc91eb21ab/BgApiDriver/BgApi.cs#L170.

You have to know the serial port your USB BLE dongle will mount itself to, ex. "COM3" and "COM5".

**Comment by jainchethan87** [comment]
Thanks for the quick reply appreciate it. 

I am assuming one ble dongle mounts as one com port on the machine. I am asking if there is just one dongle , can I connect to multiple peripherals at the same time? 
One dongle to multiple ble devices at the same time.
Please let me know if you need more information

**Comment by ahouben** [comment]
> I am assuming one ble dongle mounts as one com port on the machine

yes.

> I am asking if there is just one dongle , can I connect to multiple peripherals at the same time?

Yes, it seems the BLE112D supports up to 8 simultaneous connections, see https://moosh.im/2018/03/how-to-get-the-bled112-to-connect-to-8-devices/.

This is more of a protocol and/or product question that you might want to search for on the web to get more precise information instead of asking me, really 😃

**Comment by jainchethan87** [comment]
Well, I know BLE supports concurrent connections. I was referring to your code, can it handle multiple connections or not?

**Comment by ahouben** [comment]
Yes, it can. The code supports all of the BLE commands and events that the BGAPI exposes through a single buffer when communicating with the serial port.

You have to do all of the command invocations and implement the callback handling for the events. The relevant stubs are auto-generated for you, you just need to fill them with life.

**Comment by jainchethan87** [comment]
sounds good, I will try to implement them. Thanks for the  help.

**Comment by ahouben** [comment]
Seems to have been solved in the meantime, closing for now.
